services:
  potigol:
    build: .
    platform: linux/amd64
    volumes:
      - ./codigo:/workspace
    ports:
      - "8001:8001"
    restart: unless-stopped
    mem_limit: 256m
    cpus: "0.4"

networks:
  default:
    external:
      name: prod_net

